name: 'Build and Push Docker Image'
description: 'Builds and pushes a Docker image to the registry'
runs:
  using: "composite"
  steps:
    - name: Get repository name
      run: |
        REPO=$(echo "${{ GITHUB_REPOSITORY }}" | cut -d'/' -f2)

    - name: Build Docker Image
      shell: bash
      run: |
        docker build --network=host --pull -t "${{ env.REGISTRY }}/${{ env.REPO }}:${{ GITHUB_SHA }} " -f .infra/Dockerfile --build-arg BRANCH="${{ GITHUB_REF }}" .

    - name: Push Docker Image
      shell: bash
      run: |
        docker push "${{ env.REGISTRY }}/${{ env.REPO }}:${{ GITHUB_SHA }} "
        docker push "${{ env.REGISTRY }}/${{ env.REPO }}:${{ GITHUB_REF }} "
