name: 'Run Pre-Commit Hooks'
description: 'Runs pre-commit hooks, commits, and pushes changes.'

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pre-commit
      shell: bash
      run: pip install pre-commit

    - name: pre-commit autoupdate
      shell: bash
      run: pre-commit autoupdate

    - name: Set up Git
      shell: bash
      run: |
        git fetch
        git reset --hard origin/${{ github.ref_name }}
        git pull origin ${{ github.ref_name }}
        git config --global user.email "github-actions@deepalert.ai"
        git config --global user.name "GitHub Actions"

    - name: Run Pre-Commit Hooks
      shell: bash
      run: |
        for i in {1..5}; do pre-commit run --all-files && break || echo "Attempt $i failed... retrying."; done

    - name: Commit and Push Changes
      shell: bash
      run: |
        git add -A .
        git diff --cached --exit-code && echo "No changes to commit" || {
          git commit -m "Someone didn't pre-commit - running formatting"
          git push origin HEAD:${{ github.ref_name }}
        }
