name: 'Deploy to Kubernetes'
description: 'Deploys Kubernetes deployment by restarting it.'
inputs:
  kubeconfig:
    description: 'Base64 encoded Kubernetes configuration'
    required: true
  namespace_prefix:
    description: 'Kubernetes namespace prefix'
runs:
  using: "composite"
  steps:
    - name: Configure env variables
      shell: bash
      run: |
        REPO_NAME="${{ github.repository }}"
        DEPLOYMENT_NAME=$(echo "$REPO_NAME" | sed 's/.*\///' | tr '_' '-')
        echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV
        NS_PREFIX=${{ inputs.namespace_prefix }}
        PREFIX=${NS_PREFIX:-"deepalert"}

    - name: Decode and configure kubectl
      shell: bash
      run: |
        echo "${{ inputs.kubeconfig }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

    - name: Restart Kubernetes deployment
      shell: bash
      run: |
        kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}  -n ${{ env.PREFIX }}-${{ GITHUB_REF }}
