name: 'Deploy to Kubernetes'
description: 'Deploys Kubernetes deployment by restarting it.'
inputs:
  kubeconfig:
    description: 'Base64 encoded Kubernetes configuration'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set deployment name based on repository name
      shell: bash
      run: |
        REPO_NAME="${{ github.repository }}"
        DEPLOYMENT_NAME=$(echo "$REPO_NAME" | sed 's/.*\///' | tr '_' '-')
        echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV

    - name: Decode and configure kubectl
      shell: bash
      run: |
        echo "${{ inputs.kubeconfig }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml

    - name: Restart Kubernetes deployment
      shell: bash
      run: |
        kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}  -n deepalert-${{ GITHUB_REF }}
