on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pre-commit
      - name: Authenticate GCP
        uses: google-github-actions/auth@v0.6.0
        with:
            credentials_json: ${{ secrets.GCP_KEY }}
      - uses: ./.github/actions/build-docker

  deploy:
    runs-on: ubuntu-22.04
    permissions:
        contents: write
    needs: build

    steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/deploy-k8s
