on:
  workflow_call:
    secrets:
      gcp_provider:
        required: true
  push:
    branches:
      - main
      - staging
      - preprod

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.gcp_provider }}'
          project_id: '${{ vars.PROD_PROJECT_ID}}'

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ vars.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}" -f .infra/Dockerfile --build-arg BRANCH="${{ github.ref_name }}" .
          docker tag "${{ vars.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}" "${{ vars.REGISTRY }}/${{ github.event.repository.name }}:${{ github.ref_name }}"

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ vars.REGISTRY }}/${{ github.event.repository.name }}:${{ github.sha }}"
          docker push "${{ vars.REGISTRY }}/${{ github.event.repository.name }}:${{ github.ref_name }}"
