on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate GCP
        uses: google-github-actions/auth@v0.6.0
        with:
            credentials_json: ${{ secrets.GCP_KEY }}

      - name: Get repository name
        shell: bash
        run: |
          REPO=$(echo "${{ inputs.repository }}" | cut -d'/' -f2)

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ env.REGISTRY }}/${{ env.REPO }}:${{ inputs.sha }} " -f .infra/Dockerfile --build-arg BRANCH="${{ inputs.branch }}" .

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.REPO }}:${{ inputs.sha }} "
          docker push "${{ env.REGISTRY }}/${{ env.REPO }}:${{ inputs.branch }} "
