on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: '.infra/Dockerfile'
      name:
        required: false
        type: string
    secrets:
      gcp_provider:
        required: true
      args:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "NAME=${{ inputs.name || github.event.repository.name }}" >> $GITHUB_ENV
          echo "REGISTRY=${{ vars.REGION }}-docker.pkg.dev/${{ inputs.project_id }}/${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.gcp_provider }}'
          project_id: '${{ inputs.project_id}}'

      - run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ env.REGISTRY }}/${{ env.NAME }}:${{ github.sha }}" -f ${{ inputs.dockerfile }} --build-arg BRANCH="${{ github.ref_name }}" --build-arg REGISTRY="${{ env.REGISTRY }}" ${{ secrets.args }} .
          docker tag "${{ env.REGISTRY }}/${{ env.NAME }}:${{ github.sha }}" "${{ env.REGISTRY }}/${{ env.NAME }}:${{ github.ref_name }}"

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.NAME }}:${{ github.sha }}"
          docker push "${{ env.REGISTRY }}/${{ env.NAME }}:${{ github.ref_name }}"
