on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      sha:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate GCP
        uses: google-github-actions/auth@v0.6.0
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Docker Auth
        shell: bash
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.sha }}" -f .infra/Dockerfile --build-arg BRANCH="${{ inputs.branch }}" .
          docker tag "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.sha }}" "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.branch }}"

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.sha }}"
          docker push "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.branch }}"
