on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
    secrets:
      gcp_provider:
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Get registry
        run: |
          echo "REGISTRY=${{ vars.REGION }}-docker.pkg.dev/${{ inputs.project_id }}/${{ github.ref_name }}/${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.gcp_provider }}'
          project_id: '${{ inputs.project_id}}'

      - name: Configure Docker Authentication
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ env.REGISTRY }}:${{ github.sha }}" -f .infra/Dockerfile --build-arg BRANCH="${{ github.ref_name }}" .
          docker tag "${{ env.REGISTRY }}:${{ github.sha }}" "${{ env.REGISTRY }}:${{ github.ref_name }}"

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ env.REGISTRY }}:${{ github.sha }}"
          docker push "${{ env.REGISTRY }}:${{ github.ref_name }}"
