on:
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3  # Checkout the caller repository
      - uses: actions/checkout@v3  # Checkout the global_actions repository
        with:
          repository: deepalertai/global_actions
          path: global_actions
      - name: Authenticate GCP
        uses: google-github-actions/auth@v0.6.0
        with:
            credentials_json: ${{ secrets.GCP_KEY }}

      - uses: ./global_actions/.github/actions/pre-commit
      - uses: ./global_actions/.github/actions/build-docker
