on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        type: string
      sha:
        required: true
        type: string
    secrets:
      gcp_provider:
        required: true
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Debug GCP_KEY
        run: |
          KEY_START=$(echo "${{ secrets.gcp_provider }}" | head -c 10)
          echo "Key: $KEY_START"

      - name: Authenticate GCP
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.gcp_provider }}'

      - name: Verify gcloud Account
        run: gcloud auth list

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.sha }}" -f .infra/Dockerfile --build-arg BRANCH="${{ inputs.branch }}" .
          docker tag "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.sha }}" "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.branch }}"

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.sha }}"
          docker push "${{ vars.REGISTRY }}/${{ inputs.repository }}:${{ inputs.branch }}"
