on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate GCP
        uses: google-github-actions/auth@v0.6.0
        with:
            credentials_json: ${{ secrets.GCP_KEY }}

      - name: Get repository name
        shell: bash
        run: |
          REPO=$(echo "${{ GITHUB_REPOSITORY }}" | cut -d'/' -f2)

      - name: Build Docker Image
        shell: bash
        run: |
          docker build --network=host --pull -t "${{ env.REGISTRY }}/${{ env.REPO }}:${{ GITHUB_SHA }} " -f .infra/Dockerfile --build-arg BRANCH="${{ GITHUB_REF }}" .

      - name: Push Docker Image
        shell: bash
        run: |
          docker push "${{ env.REGISTRY }}/${{ env.REPO }}:${{ GITHUB_SHA }} "
          docker push "${{ env.REGISTRY }}/${{ env.REPO }}:${{ GITHUB_REF }} "
