on:
  workflow_call:
    inputs:
      namespace_prefix:
        type: string
    secrets:
      kube_token:
        required: true
      kube_server:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
        contents: write

    steps:
      - name: Configure env variables
        shell: bash
        run: |
          REPO_NAME="${github.event.repository.name#*/}"
          echo "DEPLOYMENT_NAME=${REPO_NAME//_/-}" >> $GITHUB_ENV
          PREFIX=${{ inputs.namespace_prefix || 'deepalert' }}
          echo "PREFIX=$PREFIX" >> $GITHUB_ENV

      - name: Configure kubectl authentication
        shell: bash
        run: |
          kubectl config set-cluster github-actions \
            --server=${{ secrets.kube_server }} \
            --insecure-skip-tls-verify=true

          kubectl config set-credentials github-actions \
            --token=${{ secrets.kube_token }}_${{ github.ref_name }}

          kubectl config set-context github-actions \
            --cluster=github-actions \
            --user=github-actions \
            --namespace=${{ env.PREFIX }}-${{ github.ref_name }}

          kubectl config use-context github-actions

          kubectl cluster-info

      # - name: Restart Kubernetes deployment
      #   shell: bash
      #   run: |
      #     kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}  -n ${{ env.PREFIX }}-${{ github.ref_name }}
