on:
  workflow_call:
    inputs:
      namespace_prefix:
        type: string
    secrets:
      kube_token:
        required: true
      kube_server:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
        contents: write

    steps:
      - name: Configure env variables
        shell: bash
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          DEPLOYMENT_NAME=$(echo "$REPO_NAME" | sed 's/.*\///' | tr '_' '-')
          echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV
          PREFIX=${{ inputs.namespace_prefix || 'deepalert' }}
          echo "PREFIX=$PREFIX" >> $GITHUB_ENV

      - name: Configure kubectl authentication
        shell: bash
        run: |
          kubectl config set-cluster github-actions \
            --server=${{ secrets.kube_server }} \
            --insecure-skip-tls-verify=true
          kubectl config set-credentials github-actions \
            --token=${{ secrets.kube_token }}
          kubectl config set-context github-actions \
            --cluster=github-actions \
            --user=github-actions \

          kubectl config use-context github-actions
          kubectl auth can-i get deployments -n ${{ env.PREFIX }}-${{ github.ref_name }}

      # - name: Restart Kubernetes deployment
      #   shell: bash
      #   run: |
      #     kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}  -n ${{ env.PREFIX }}-${{ github.ref_name }}
