on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      namespace_prefix:
        type: string

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
        contents: write

    steps:
      - name: Configure env variables
        shell: bash
        run: |
          REPO_NAME="${{ github.repository }}"
          DEPLOYMENT_NAME=$(echo "$REPO_NAME" | sed 's/.*\///' | tr '_' '-')
          echo "DEPLOYMENT_NAME=$DEPLOYMENT_NAME" >> $GITHUB_ENV
          NS_PREFIX=${{ inputs.namespace_prefix }}
          PREFIX=${NS_PREFIX:-"deepalert"}
          echo "PREFIX=$PREFIX" >> $GITHUB_ENV

      - name: Decode and configure kubectl
        shell: bash
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Restart Kubernetes deployment
        shell: bash
        run: |
          kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }}  -n ${{ env.PREFIX }}-${{ inputs.branch }}
