on:
  workflow_call:
    inputs:
      target_repo:
        required: true
        type: string
    secrets:
      workflow_token:
        required: true

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - run: |
          curl --fail --silent --show-error -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.workflow_token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"event_type": "restart-trigger", "client_payload": {"branch": "${{ github.ref }}"}}' \
            https://api.github.com/repos/deepalertai/${{ inputs.target_repo }}/dispatches
